### ISSUE TITLE
Once animation is played, keep final frame and remove freezeframe.

### ISSUE THREAD

**Issue by zachNich** [ctrl-freaks/freezeframe.js#24]
Hello, so I'm working on a project using this that has graphs that animate and then stop on the last frame rather than looping. I know I could time it exactly and extract the last frame with .selector, but I thought it'd just be easier if you could just disable freezeframe on a particular gif after it's activated. Currently I'm doing this by just removing the classes added by freezeframe after it's animated, but it'd be cool if there was a feature that you could specify how many times the animation ran (ie "num_loops" , "1") and then just show the final frame.

**Comment by chrisantonellis** [comment]
@zachNich sorry but what you describe is not possible :( Because of the way the first frame of the .gif is captured ( restarting the gif and immediately writing to a canvas ) there is no way for freezeframe to know the length of a .gif, the number of frames etc... and therefore no way to pause on a specific frame or stop after a certain number of loops.

You *could* extend freezeframe to accept data about the .gifs such as length of gif in seconds, number of frames, length of frames in seconds and probably achieve the functionality you are describing, but this is not a current goal of the plugin.

Thanks!
