### ISSUE TITLE
Doesn't work with my exported transparent gif from photoshop

### ISSUE THREAD

**Issue by slzr** [ctrl-freaks/freezeframe.js#29]
I really love your work, but for some reason the plugin doesn't work for me, I take  one of the images that you used in the examples and works fine, but with my gif doesn't, the gif doesn't stop/play, it just keeping playing in loop forever, I don't know if there is something in my exporting configuration in photoshop but i use:

![Photoshop Export conf](http://i.imgur.com/F3GaHWQ.png)

``` html
<img class="freezeframe freezeframe-responsive sec-1-img" src="test2.gif">
```

``` javascript
third = new freezeframe('.sec-1-img').capture().setup();
$('.btn-img').click(function(e){
  e.preventDefault();
  third.trigger();
});
```

I was following the third example, and i have this behavior with the transparent gif and never stop/play
![transparent bg bug](http://g.recordit.co/5etUURExXA.gif)

**Comment by chrisantonellis** [comment]
Sorry for the late response @slzr but the issue was with how you were exporting the image from Photoshop. If you look in the bottom right corner of the image you posted above, there is an option "Looping Options" that currently says "Forever." To get the animation to only loop once, you would need to select that from the dropdown
