### ISSUE TITLE
Start Image Fails to load IOS Chrome

### ISSUE THREAD

**Issue by ngtjah** [ctrl-freaks/freezeframe.js#3]
The start image doesn't seem to load on an IPad in Chrome.  It looks like it is loading but then it loads a blank white image with the play button.

It works on desktop chrome and android chrome just fine. This leads me to believe the problem is within the IPad version of Chrome but I'm not sure.

![photo1](https://cloud.githubusercontent.com/assets/3903697/2747668/eb317568-c77b-11e3-94d0-4996837f901f.png)

**Comment by samselikoff** [comment]
@chrisantonellis I ran into this issue today as well. I solved the CORS issues by having S3 return the access-control headers. Everything's working on my dev machine but on chrome on my iPhone, I'm running into the same problem - plain white screen instead of placeholder image. In safari it works great. 

Any ideas?

**Comment by sstbck** [comment]
Same here. But it extends to the Mac version of Chrome as well. White background instead of placeholder. Nothing happens on hover. But sometimes I see a very fast flickering, then the image goes away.
